-- 코드를 입력하세요
WITH SALE_TB AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES_AM
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
)
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.SALES_AM * B.PRICE) AS TOTAL_SALES
FROM AUTHOR A
JOIN (SELECT BB.BOOK_ID, BB.AUTHOR_ID, BB.CATEGORY, SS.SALES_AM, BB.PRICE
     FROM BOOK BB
     JOIN SALE_TB SS ON BB.BOOK_ID = SS.BOOK_ID) B ON A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;