-- 코드를 입력하세요
SELECT CART_ID
FROM (
    SELECT CART_ID,
        DENSE_RANK() OVER (PARTITION BY CART_ID ORDER BY NAME) AS C
    FROM CART_PRODUCTS
    WHERE NAME = "Milk" OR NAME = "Yogurt"
    ORDER BY CART_ID
) t
WHERE C>=2
ORDER BY CART_ID;