-- 코드를 입력하세요
WITH TB AS (SELECT ONLINE_SALE_ID AS ID, USER_ID, PRODUCT_ID,
    SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE
    WHERE SALES_DATE>='2022-03-01' AND SALES_DATE<'2022-04-01'
UNION ALL
SELECT OFFLINE_SALE_ID AS ID, NULL AS USER_ID, PRODUCT_ID,
    SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE
    WHERE SALES_DATE>='2022-03-01' AND SALES_DATE<'2022-04-01'
)
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d'), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM TB
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;