-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT INS.ANIMAL_ID, INS.NAME, OUTS.DATETIME - INS.DATETIME AS T
    FROM ANIMAL_INS AS INS
    JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
) ANIMAL
ORDER BY T DESC
LIMIT 2;
