-- 코드를 입력하세요
WITH RENT_NOTAVAILABLE AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE*30) * (1-DR.DISCOUNT_RATE*0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (SELECT CAR_TYPE, SUBSTRING(DISCOUNT_RATE,1,LENGTH(DISCOUNT_RATE)) AS DISCOUNT_RATE
     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
     WHERE SUBSTRING(DURATION_TYPE,1,2)  ='30'
     ) DR ON C.CAR_TYPE = DR.CAR_TYPE
WHERE C.CAR_ID NOT IN (SELECT * FROM RENT_NOTAVAILABLE)
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY C.CAR_ID;