-- 코드를 입력하세요
# SELECT FOOD_TYPE, REST_ID, REST_NAME, MAX(FAVORITES) AS `FAVORITES`
# FROM REST_INFO
# WHERE (FOOD_TYPE, REST_ID) IN (
#     SELECT FOOD_TYPE, REST_ID, RANK() OVER (PARTITION BY FOOD_TYPE
#                                            ORDER BY FAVORITES DESC) AS RNK
#     FROM REST_INFO)
WITH RANKED AS (SELECT REST_ID, 
        RANK() OVER (PARTITION BY FOOD_TYPE
                    ORDER BY FAVORITES DESC) AS RNK
FROM REST_INFO
)
SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN RANKED RKD ON R.REST_ID = RKD.REST_ID
WHERE RKD.RNK = 1
ORDER BY FOOD_TYPE DESC;