-- 코드를 입력하세요
SELECT H.CAR_ID, CASE
                WHEN SUM(A.AVAILABILITY)>=1 THEN '대여중'
                ELSE '대여 가능'
                END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN (SELECT HISTORY_ID, CASE
            WHEN DATEDIFF(START_DATE,'2022-10-16')<=0 AND
                DATEDIFF(END_DATE,'2022-10-16')>=0 THEN 1
            ELSE 0
      END AS AVAILABILITY
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     ) AS A ON H.HISTORY_ID = A.HISTORY_ID
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;
