# -- 코드를 입력하세요
WITH HEAVY_HOST AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID)>=2
)
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
JOIN HEAVY_HOST HH ON P.HOST_ID = HH.HOST_ID
ORDER BY P.ID;

# SELECT ID, NAME, HOST_ID
#     FROM PLACES
#     GROUP BY HOST_ID
#     HAVING COUNT(HOST_ID)>=2)