-- 코드를 입력하세요
# SELECT date_format(produce_date,'%Y-%m')
# from food_order;

SELECT O.PRODUCT_ID,P.PRODUCT_NAME,SUM(O.AMOUNT*P.PRICE) AS `TOTAL_SALES`
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE DATE_FORMAT(O.produce_date,'%Y-%m')='2022-05'
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,O.PRODUCT_ID ASC;