-- 코드를 입력하세요
WITH HISTORY AS (
    SELECT HISTORY_ID, CAR_ID, 
        DATEDIFF(END_DATE,START_DATE)+1 AS DURATION,
        CASE
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT H.HISTORY_ID,
    FLOOR(H.DURATION * C.DAILY_FEE * (1-0.01*IFNULL(DISCOUNT_RATE,0))) AS FEE
FROM HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
    ON C.CAR_TYPE = DP.CAR_TYPE AND DP.DURATION_TYPE = H.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;