-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM HOURS WHERE H<23
)
SELECT HOURS.H, IFNULL(CO,0)
FROM HOURS
LEFT JOIN (
    SELECT HOUR(DATETIME) AS H, COUNT(HOUR(DATETIME)) AS CO
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) C ON HOURS.H = C.H;