WITH COUNTS AS (
SELECT COUNT(*) AS C, MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
),
RANKED AS (
SELECT MEMBER_ID, C, RANK() OVER (ORDER BY C DESC) AS RNK
FROM COUNTS
)
SELECT M.MEMBER_NAME AS `MEMBER_NAME`,
        R.REVIEW_TEXT AS `REVIEW_TEXT`,
        DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS `REVIEW_DATE`
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M ON R.MEMBER_ID = M.MEMBER_ID
JOIN RANKED RKD ON R.MEMBER_ID = RKD.MEMBER_ID
WHERE RKD.RNK = 1
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;