# -- 코드를 입력하세요
WITH RANK_TABLE AS (
    SELECT PRODUCT_ID, CATEGORY, PRICE, PRODUCT_NAME,
        RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
)
SELECT CATEGORY,PRICE AS `MAX_PRICE`, PRODUCT_NAME
FROM RANK_TABLE
WHERE RNK=1
ORDER BY PRICE DESC;
# SELECT * FROM FOOD_PRODUCT
# WHERE CATEGORY = "과자";